@baseUrl = http://localhost:3000

### 管理员注册
POST {{baseUrl}}/admins/register
Content-Type: application/json

{
  "user_name": "user3",
  "password": "12345678"
}

// TODO: 登录成功返回token
### 管理员登录
POST {{baseUrl}}/admins/login
Content-Type: application/json

{
  "user_name": "user1",
  "password": "123456"
}

// TODO: 利用token信息更新
### 管理员信息更新
PUT {{baseUrl}}/admins/5e9e9886696df92e9c96be67
Content-Type: application/json

{
  "password": "123456",
  "city":"上海"
}

### 获取管理员列表
GET {{baseUrl}}/admins?offset=0&limit=1

### 删除管理员
DELETE {{baseUrl}}/admins/5e9bd7dceddc242a34db8631

### 获取商家列表
GET {{baseUrl}}/v1/merchants?offset=0&limit=1

### 获取商家信息
GET {{baseUrl}}/v1/merchants/5e9bd936f0161441ac9da486

### 删除商家
DELETE {{baseUrl}}/v1/merchants/5e9bd936f0161441ac9da486

### 新建商家
POST {{baseUrl}}/v1/merchants
Content-Type: application/json

{
    "shop_name":"同福客栈",
    "register_date":"2020-04-18T13:52:39",
    "address":"西湖路万达广场B1层436号",
    "phone":"18446905856",
    "introduction":"同福客栈是电视剧《武林外传》中的客栈名称，是本电视剧故事发生的主要地点。"
} 

### 更新商家
PUT  {{baseUrl}}/v1/merchants/5e9d291c08d9cf3a8878babb
Content-Type: application/json

{
    "address":"西湖路万达广场B1层436号",
    "phone":"18725451268"
} 
