@baseUrl = http://localhost:3000/api/v1
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYTQ0ZTgzZWQ5ZWU4MWNmNDg5NWIwZSIsImlhdCI6MTU4Nzg5ODMyNCwiZXhwIjoxNTg4NTAzMTI0fQ.yKNeERe283DA9roZGA8HJfxFI30V9SnUAIQGZGq98Lk
### 用户登录
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_name": "user1",
  "password": "123456"
}

### 更新用户信息
PUT {{baseUrl}}/users/5ea44f0a4795991a34a80ba6
{{authorization}}
Content-Type: application/json

{
  "password":"12345678",
  "new_password":"123456"
}

### 管理员注册
POST {{baseUrl}}/register/admin
Content-Type: application/json

{
  "user_name": "user3",
  "password": "12345678"
}

### 获取管理员信息
GET {{baseUrl}}/admins/5ea44e83ed9ee81cf4895b0f
{{authorization}}




### 更新管理员信息
PUT {{baseUrl}}/admins/5ea44e83ed9ee81cf4895b0f
{{authorization}}
Content-Type: application/json

{ 
  "name":"马云",
  "city":"上海"
}

### 获取管理员列表
GET {{baseUrl}}/admins?offset=0&limit=1
{{authorization}}

### 删除管理员
DELETE {{baseUrl}}/admins/5ea44f90fc6be23c940fbf9c
{{authorization}}

# ### 获取商家列表
# GET {{baseUrl}}/merchants?offset=0&limit=1
# {{authorization}}

# ### 获取商家信息
# GET {{baseUrl}}/merchants/5e9bd936f0161441ac9da486
# {{authorization}}

# ### 删除商家
# DELETE {{baseUrl}}/merchants/5e9bd936f0161441ac9da486
# {{authorization}}

# ### 新建商家
# POST {{baseUrl}}/merchants
# {{authorization}}
# Content-Type: application/json

# {
#     "shop_name":"同福客栈",
#     "register_date":"2020-04-18T13:52:39",
#     "address":"西湖路万达广场B1层436号",
#     "phone":"18446905856",
#     "introduction":"同福客栈是电视剧《武林外传》中的客栈名称，是本电视剧故事发生的主要地点。"
# } 

# ### 更新商家
# PUT  {{baseUrl}}/merchants/5e9d291c08d9cf3a8878babb
# {{authorization}}
# Content-Type: application/json

# {
#     "address":"西湖路万达广场B1层436号",
#     "phone":"18725451268"
# } 
